### ISSUE TITLE
AAFWriter: add support for comments

### ISSUE THREAD

**Issue by timlehr** [OpenTimelineIO/otio-aaf-adapter#22]
## Description

Currently the AAF writer doesn't translate user comments generated by the AAF reader (or manually by the user).

The adapter should translate comments from the clip / media reference onto the `MasterMob` and comments from the timeline onto the `CompositionMob`.

**Comment by jminor** [comment]
Related: support for an optional `comment` field on Marker was recently added to OTIO: https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1698

**Comment by timlehr** [comment]
@jminor currently the AAF Writer doesn't do markers yet, so adding support for them would be a prerequisite.
